from django.db import models

class Tournament(models.Model):
    name = models.TextField(null=True)
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    TOURNAMENT_TEMPLATE_ID = models.TextField(null=True)
    TOURNAMENT_IMAGE = models.URLField(null=True)


class Events(models.Model):
    tournament = models.ForeignKey(
        Tournament, related_name='events', on_delete=models.CASCADE, null=True)
    event_id = models.TextField(null=True)
    start_time = models.TextField(null=True)
    start_utime = models.TextField(null=True)
    stge_type = models.TextField(null=True)
    merge_stage_tupe = models.TextField(null=True)
    stage = models.TextField(null=True)
    sort = models.TextField(null=True)
    live_mark = models.TextField(null=True)
    game_time = models.TextField(null=True)
    short_name_away = models.TextField(null=True)
    away_name = models.TextField(null=True)
    away_score_current = models.TextField(null=True)
    away_score_part_1 = models.TextField(null=True)
    away_score_part_2 = models.TextField(null=True)
    away_images = models.URLField(null=True)
    short_name_home = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_score_current = models.TextField(null=True)
    home_score_part_1 = models.TextField(null=True)
    home_score_part_2 = models.TextField(null=True)
    home_images = models.URLField(null=True)
    red_cards_home = models.TextField(null=True)
    red_cards_away = models.TextField(null=True)
    yellow_cards_home = models.TextField(null=True)
    yellow_cards_away = models.TextField(null=True)


class EventId(models.Model):
    live_event_id = models.TextField(null=True)


class LiveOfEvents(models.Model):
    name = models.CharField(max_length=100)
    headers = models.CharField(max_length=100)
    name_part_1 = models.CharField(max_length=100)
    name_part_2 = models.CharField(max_length=100)
    tournament_tamplete_id = models.CharField(max_length=100)
    country_id = models.IntegerField()
    country_name = models.CharField(max_length=100)
    tournament_stage_id = models.CharField(max_length=100)
    source_type = models.IntegerField()
    has_live_table = models.IntegerField()
    standing_info = models.IntegerField()
    tamplate_id = models.CharField(max_length=100)
    tournament_stage_type = models.IntegerField()
    short_name = models.CharField(max_length=100)
    url = models.URLField()
    tourmanet_url = models.URLField()
    sort = models.CharField(max_length=100)
    stage_count = models.IntegerField()
    zkl = models.CharField(max_length=100)
    zku = models.CharField(max_length=100)
    tournamet_season_id = models.CharField(max_length=100)
    category_name = models.CharField(max_length=100)
    event_id = models.ForeignKey(Events, on_delete=models.CASCADE)


class TournamentHockey(models.Model):
    name = models.TextField(null=True)
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    TOURNAMENT_TEMPLATE_ID = models.TextField(null=True)
    TOURNAMENT_IMAGE = models.URLField(null=True)


class HockeyLiveEvents(models.Model):
    tournament = models.ForeignKey(
        TournamentHockey, related_name='events', on_delete=models.CASCADE, null=True)
    events_id = models.TextField(null=True)
    start_time = models.TextField(null=True)
    start_utime = models.TextField(null=True)
    stge_type = models.TextField(null=True)
    merge_stage_tupe = models.TextField(null=True)
    stage = models.TextField(null=True)
    sort = models.TextField(null=True)
    live_mark = models.TextField(null=True)
    has_lineps = models.TextField(null=True)
    stage_start_time = models.TextField(null=True)
    game_time = models.TextField(null=True)
    playing_in_sets = models.TextField(null=True)
    recent_overs = models.TextField(null=True)
    shortname_home = models.TextField(null=True)
    home_participant_ids = models.TextField(null=True)
    home_participant_types = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_participant_name_one = models.TextField(null=True)
    home_event_participant_id = models.TextField(null=True)
    home_goal_var = models.TextField(null=True)
    home_current_score = models.TextField(null=True)
    home_score_part_1 = models.TextField(null=True)
    home_score_part_2 = models.TextField(null=True, blank=True)
    home_score_part_3 = models.TextField(null=True, blank=True)
    home_images = models.TextField(null=True)
    shortname_away = models.TextField(null=True)
    away_participant_ids = models.TextField(null=True)
    away_participant_types= models.TextField(null=True)
    away_name = models.TextField(null=True)
    away_participant_name_one  = models.TextField(null=True)
    away_event_participant_id = models.TextField(null=True)
    away_goal_var = models.TextField(null=True)
    away_current_score= models.TextField(null=True)
    away_score_fullL = models.TextField(null=True)
    away_score_part_1 = models.TextField(null=True)
    away_score_part_2 = models.TextField(null=True, blank=True)
    away_score_part_3 = models.TextField(null=True, blank=True)
    away_images= models.TextField(null=True)


class EndedMatch(models.Model):
    tournamet_name = models.TextField(null=True)
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    event_id = models.TextField(null=True)
    stage_tyoe = models.TextField(null=True)
    round = models.TextField(null=True)
    shortname_home = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_score_current = models.TextField(null=True)
    home_score_part_1 = models.TextField(null=True)
    home_score_part_2 = models.TextField(null=True)
    home_images = models.TextField(null=True)
    shortname_away = models.TextField(null=True)
    name_away = models.TextField(null=True)
    away_score_current = models.TextField(null=True)
    away_score_full = models.TextField(null=True)
    away_score_part_1 = models.TextField(null=True)
    away_score_part_2 = models.TextField(null=True)
    away_images = models.TextField(null=True)


class Scheduled(models.Model):
    tournament = models.TextField(null=True)
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    event_id = models.TextField(null=True)
    start_time = models.TextField(null=True)
    start_utime = models.TextField(null=True)
    shortname_home = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_images = models.TextField(null=True)
    shortname_away = models.TextField(null=True)
    name_away = models.TextField(null=True)
    away_images = models.TextField(null=True)


class All(models.Model):
    tournamet_name = models.TextField(null=True)
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    event_id = models.TextField(null=True)
    stage_type = models.TextField(null=True)
    round = models.TextField(null=True)
    shortname_home = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_score_current = models.TextField(null=True)
    home_score_part_1 = models.TextField(null=True)
    home_score_part_2 = models.TextField(null=True)
    home_images = models.TextField(null=True)
    shortname_away = models.TextField(null=True)
    name_away = models.TextField(null=True)
    away_score_current = models.TextField(null=True)
    away_score_full = models.TextField(null=True)
    away_score_part_1 = models.TextField(null=True)
    away_score_part_2 = models.TextField(null=True)
    away_images = models.TextField(null=True)


class AllHockey(models.Model):
    tournamet_name = models.TextField(null=True)
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    event_id = models.TextField(null=True)
    stage_type = models.TextField(null=True)
    round = models.TextField(null=True)
    shortname_home = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_score_current = models.TextField(null=True)
    home_score_part_1 = models.TextField(null=True)
    home_score_part_2 = models.TextField(null=True)
    home_score_part_3 = models.TextField(null=True)
    home_images = models.TextField(null=True)
    shortname_away = models.TextField(null=True)
    name_away = models.TextField(null=True)
    away_score_current = models.TextField(null=True)
    away_score_full = models.TextField(null=True)
    away_score_part_1 = models.TextField(null=True)
    away_score_part_2 = models.TextField(null=True)
    away_score_part_3 = models.TextField(null=True)
    away_images = models.TextField(null=True)


class ScheduledHockey(models.Model):
    tournament = models.TextField(null=True)
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    event_id = models.TextField(null=True)
    start_time = models.TextField(null=True)
    start_utime = models.TextField(null=True)
    shortname_home = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_images = models.TextField(null=True)
    shortname_away = models.TextField(null=True)
    name_away = models.TextField(null=True)
    away_images = models.TextField(null=True)


class EndedHockey(models.Model):
    tournament_stage_type = models.TextField(null=True)
    tournament_imng = models.TextField(null=True)
    event_id = models.TextField(null=True)
    stage_tyoe = models.TextField(null=True)
    rounds = models.TextField(null=True)
    shortname_home = models.TextField(null=True)
    home_name = models.TextField(null=True)
    home_score_current = models.TextField(null=True)
    home_score_part_1 = models.TextField(null=True)
    home_score_part_2 = models.TextField(null=True)
    home_score_part_3 = models.TextField(null=True)
    home_images = models.TextField(null=True)
    shortname_away = models.TextField(null=True)
    name_away = models.TextField(null=True)
    away_score_current = models.TextField(null=True)
    away_score_full = models.TextField(null=True)
    away_score_part_1 = models.TextField(null=True)
    away_score_part_2 = models.TextField(null=True)
    away_score_part_3 = models.TextField(null=True)
    away_images = models.TextField(null=True)
