# Generated by Django 3.1.10 on 2023-10-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='live_mark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='merge_stage_tupe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='sort',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='stage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='stge_type',
            field=models.TextField(null=True),
        ),
    ]
